### PR TITLE
Added a Markdown file where I describe why Bento ML is useful and list alternatives

### LINKED ISSUE #14: Sum up why BentoML is useful and it's alternatives

### PR DESCRIPTION
**Pull request by Namra-Jabeen**

### CODE REVIEW

**Comment by halvgaard** [comment]
How does it relate to ZenML? Do they integrate BentoML?

**Comment by halvgaard** [comment]
Why do you have all the previous commits in this PR? Please sync main branches between this repo and your fork.

**Comment by halvgaard** [comment]
FastAPI and KubeFlow are listed to alternatives. They are very different. So what does that mean. I still don't exactly get what to use BentoML for.

**Comment by halvgaard** [comment]
Please prepare a small 10 min presentation of BentoML with a few examples of how to use. Setup an invite for computas data scientists and let's discuss it a bit.

**Comment by Namra-Jabeen** [comment]
I did sync the main branches so I am very confused as to why it adds all the prev commits as well. 
Alright, I'll work on the presentation now.

**Review by halvgaard — APPROVED** [review]

**Pull request merged**
