### PR TITLE
Task4 - Added zenML using poetry and created a test script that runs a zenML training pipeline locally

### LINKED ISSUE #11: Add ZenML to the project using poetry

### PR DESCRIPTION
**Pull request by lukyrasocha**

### CODE REVIEW

**Review by halvgaard — CHANGES_REQUESTED** [review]
Do we need the .zen folder versioned?

**Comment by lukyrasocha** [comment]
So now I gitignored .zen folder, I hope I understood you correctly.

**Comment by halvgaard** [comment]
> So now I gitignored .zen folder, I hope I understood you correctly.

Yes I think. Please check zenml docs. I remember it's in there somewhere.

**Comment by lukyrasocha** [comment]
I couldn't find it in the docs, however in the official zenML repo they also gitignore it. Is there anything else I should fix in this PR?

**Pull request merged**
